name: Impact
favicon: null
layout_spectrum: 0.41319
typography_spectrum: 0.74007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58585a'
    - '#cbcbcb'
    - '#6fad4d'
    - '#29292b'
  brandStrength: 0.6875
  lightness: 0.5335795609280467
  saturation: 0.5268561998382211
  rhythmicContrast: 0.8331911896821111
purpose: []
